name: urban-flood-stress
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - geopandas
  - shapely
  - pyproj
  - proj
  - gdal
  - rasterio
  - rioxarray
  - contextily
  - scikit-learn
  - matplotlib
  - networkx
  - pyarrow
  - python-igraph
  - pgmpy
  - opt_einsum
  - pyro-ppl
  - ipykernel
  - nbconvert
  - sodapy
  - pytest
  - black
  - ruff
  - sphinx
  - myst-parser
  - pip
  - pip:
      - -e .